@startuml
'https://plantuml.com/sequence-diagram

class Customer{
+name
+address
+job
+card number
+pin
+verifyPassword()
}

class Bank{
+code
+address
+manages()
+maintains()
}

class ATM{
+location
+managedby
+identifies()
+transctions()
}

class Account{
+number
+balance
+deposit()
+withdraw()
+create Transaction()
}

class ATM_Transaction{
+transaction id
+date
+type
+amount
+post balance
+modifies()
}

class Current_Account{
+account No.
+balance
+withdraw()
}

class Saving_Account{
+account No.
+balance
}



@enduml