name: Generate Release Note
on:
  pull_request:
    # PRが閉じたタイミングで実行
    types:
      - closed
    # mainブランチのみを対象とする
    branches:
      - feature/test_release

permissions:
  contents: read

jobs:
  release:
    permissions:
      # write permission is required to create a github release
      contents: write
      # リリースノートを書くためwrite用のpermissionを付与
      pull-requests: write
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Genterate Release Note
        env:
          # このトークンは自動生成されるのでsecretsを登録する必要ない
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PRのタイトルと内容をRelease内容に追加する
          #RELEASE_TAG: ${{ github.event.pull_request.head.ref }}
          RELEASE_TAG: ${{ RESOLVED_VERSION }}
          
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          version: ${{ env.RELEASE_TAG }}
          publish: true
        
        
